### ISSUE TITLE
Compile multiple files in one push

### ISSUE THREAD

**Issue by wmboyles** [vinay0410/tectonic-action#12]
I have a TeX project with the following directory structure:
```
folder1
    main.tex
folder2
    main.tex
folder3
    main.tex
```
I'd like to use the action to compile all of these files and have the resulting PDFs appear in the appropriate folder like so:
```
folder1
    main.tex
    main.pdf
folder2
    main.tex
    main.pdf
folder3
    main.tex
    main.pdf
```
I'm OK with all of the files being recompiled whenever any one changes, but it would be most convenient if any changes were pushed in one commit instead of 3. Is there a way to accomplish this? Can I add multiple .tex files to the `tex-path` argument? Could I have one step for each document I want to compile and only have the `push` argument as 'yes' on the final step?

Thanks for the action. I know it'll be really useful for me.

**Comment by wmboyles** [comment]
I see that #6 mentions being able to do this by running multiple jobs with different file paths, but would all the changes be pushed in a single commit?

**Comment by vinay0410** [comment]
@wmboyles , I don't think it's currently possible using tectonic-action alone.
Although, this can be accomplished using multiple actions.

Create 3 jobs of tectonic-action and pass `push` as `no`.
These 3 jobs will generate 3 artifacts ( 3 pdf files ).

Fourth job will just push these 3 artifacts to their desired location. You can use a third party job to accomplish this part.

**Comment by wmboyles** [comment]
Thanks for the advice. I was able to do that.
