### ISSUE TITLE
A better way to add fonts

### ISSUE THREAD

**Issue by pineapplehunter** [vinay0410/tectonic-action#9]
I wanted to use this action to check my LaTeX file, but because I used Japanese fonts in my file It didn't compile.
I saw that this was using docker, so I forked this repo and added one line in Dockerfile before the entry as a workaround.

```
RUN apt update -y && apt install fonts-ipafont -y
```

Is there a better way to add fonts to the action?
Can it be a option of some kind?

Thanks!

**Comment by vinay0410** [comment]
@pineapplehunter , I have updated the image (`vinay0410/tectonic-image:latest`), please see if this action is working for you without the above workaround.

**Comment by pineapplehunter** [comment]
@vinay0410 I tried it out, but it didn't work.
I think you added `fonts-ipafont` here.
https://github.com/vinay0410/tectonic-docker/blob/768154a5d4cd04bf2a74990344ee971eb4fd308a/Dockerfile#L3
But I can't access the font in the final image.
Can you move the install to this line?
https://github.com/vinay0410/tectonic-docker/blob/768154a5d4cd04bf2a74990344ee971eb4fd308a/Dockerfile#L24

**Comment by vinay0410** [comment]
Good point @pineapplehunter .
I guess it wasn't being copied to the secondary image. I have made the change. Please try again in 20 mins.
It will take that much time for image to be built and pushed.

**Comment by pineapplehunter** [comment]
@vinay0410 It successfully compiled!
Thank you!
